### ISSUE TITLE
Feature Request: Thermostat

### ISSUE THREAD

**Issue by veonua** [toddaustin07/MQTT-Discovery#2]
topics:
  int roomtemp {get} C*
  int outdoortemp {get} C*
  int setpoint {get; set} C*
  fanmode {get; set} ["auto", "quiet", "lvl_1", "lvl_2", "lvl_3", "lvl_4", "lvl_5"]
  /swingmode {get; set} ["on","off"] 
  /mode {get; set} [  "auto", "cool", "heat", "dry", "fan_only"]
  /state {get; set} ["on","off"]

by default, my implementation uses the prefix "/state" for device reporting and "/set" for setting

on/off timer would be great to have, but as far as I know, the ST presentation is cranky.

**Comment by toddaustin07** [comment]
**_by default, my implementation uses the prefix "/state" for device reporting and "/set" for setting_**

Do you have any flexibility to change your implementation?  I'm asking because currently this driver requires the subscribed topic to begin with smartthings/.

If that's not configurable for you, then would my other [MQTT Devices](https://github.com/toddaustin07/MQTTDevices) driver maybe be a better fit for what you need?

**Comment by veonua** [comment]
thanks already solved in a fork
